header:
  version: 11

machine: itx-3588j
distro: voyager
target:
  - voyager-image
  - voyager-image-weston

repos:
  bitbake:
    url: "https://git.openembedded.org/bitbake"
    commit: 734b0ea3dfe45eb16ee60f0c2c388e22af4040e0
    layers:
      .: excluded

  openembedded-core:
    url: "https://git.openembedded.org/openembedded-core"
    commit: f6de96c9fa8d0b6c81c32016f342ad93c8940d9e
    layers:
      meta:

  meta-openembedded:
    url: "git://git.openembedded.org/meta-openembedded"
    commit: 4052c97dc83d0c88fc277d6fc1815e0699020daa
    layers:
      meta-oe:

  meta-arm:
    url: "git://git.yoctoproject.org/meta-arm"
    commit: 260e3adc2bf322f52d81c0642c825088a88bb051
    layers:
      meta-arm-toolchain:
      meta-arm:

  meta-rockchip:
    url: "https://github.com/JeffyCN/meta-rockchip.git"
    commit: fefd732272a7a7d2773c0e7ed39f0e8a5ced2766

  meta-axelera:
    layers:
      meta-axelera:

local_conf_header:
  meta-axelera: |
    # Some useful lines you may want to copy to your site.conf for development
    # INHERIT += "rm_work"
    EXTRA_IMAGE_FEATURES = "debug-tweaks"
    IMAGE_FSTYPES:append = " ${RK_ROOTFS_TYPE} wic"
    RK_ROOTDEV_UUID ?= "614e0000-0000-4b53-8000-1d28000054a9"
    RK_ROOTFS_TYPE ?= "ext4"
    WKS_FILE = "generic-gptdisk.wks.in"
