header:
  version: 11

machine: itx-3588j
distro: voyager
target:
  - voyager-image

repos:
  bitbake:
    url: "https://git.openembedded.org/bitbake"
    refspec: "2.0"
    layers:
      .: excluded

  openembedded-core:
    url: "https://git.openembedded.org/openembedded-core"
    refspec: kirkstone
    layers:
      meta:

  meta-openembedded:
    url: "git://git.openembedded.org/meta-openembedded"
    refspec: kirkstone
    layers:
      meta-oe:

  meta-arm:
    url: "git://git.yoctoproject.org/meta-arm"
    refspec: kirkstone
    layers:
      meta-arm-toolchain:
      meta-arm:

  meta-rockchip:
    url: "https://github.com/JeffyCN/meta-rockchip.git"
    refspec: master

  meta-axelera:
    layers:
      meta-axelera:

local_conf_header:
  meta-axelera: |
    # Some useful lines you may want to copy to your site.conf for development
    # INHERIT += "rm_work"
    # EXTRA_IMAGE_FEATURES = "debug-tweaks"
    IMAGE_FSTYPES:append = " ${RK_ROOTFS_TYPE} wic"
    RK_ROOTDEV_UUID ?= "614e0000-0000-4b53-8000-1d28000054a9"
    RK_ROOTFS_TYPE ?= "ext4"
    WKS_FILE = "generic-gptdisk.wks.in"
